window.ECOMESSE_EXHIBITOR_URLS = {
  "一般社団法人 千葉県産業資源循環協会": "https://www.chiba-sanpai.or.jp",
  "千葉大学 予防医学センター エコチル調査千葉ユニットセンター": "https://cpms.chiba-u.jp/kodomo/",
  "自然エネルギーを広めるネットワークちば": "https://www.renet-chiba.net/",
  "なのはな生活協同組合": "https://nanohana-coop.net/",
  "（公社）千葉県浄化槽検査センター（一社）千葉県環境保全センター": "https://cjks.jp/ https://kankyohozen.com/",
  "千葉市子ども交流館": "https://www.kodomo-koryukan.jp/",
  "特定非営利活動法人ちば森づくりの会": "http://chiba-moridukuri.org",
  "フィールドミュージアム・三番瀬の会": "https://kiyofeel.home.blog/",
  "一般社団法人千葉県環境保全協議会": "https://chibakanhokyo.com/",
  "千葉工業大学分子生態工学研究室": "https://cit-lifescience.jp/murakami/index.html",
  "有限会社エムエスイー": "https://m-s^e.net/",
  "佐倉市気候変動適応センター・気象庁銚子地方気象台": "https://www.city.sakura.lg.jp/soshiki/seikatsukankyoka/kikohendo/index.html",
  "千葉大学環境ISO学生委員会": "https://env.chiba-univ.net/",
  "生活協同組合コープみらい": "https://mirai.coopnet.or.jp/",
  "千葉県地球温暖化防止活動推進センター/千葉県地球温暖化防止活動推進員": "https://www.ckz.jp/onndannka/index.html",
  "一般社団法人千葉県木材振興協会": "http://www.wood-chiba.jp/",
  "オオカミと里山を考える会": "https://japan-wolf.org",
  "（一社）日本プラスチック食品容器工業会": "https://www.japfca.jp/",
  "房総ガス協議会 環境部会": "https://www.bosogas.jp/gaiyou/gaiyou.html",
  "CAP. （キャップドット）": "https://www7a.biglobe.ne.jp/~qwerty/capdot.htm",
  "千葉県立長生高等学校サイエンス部": "https://cms2.chiba-c.ed.jp/chosei-h/",
  "成田空港活用協議会(千葉県 成田空港政策課)": "https://nrt-promo.jimdoweb.com/",
  "船橋ほたる観察会": "https://funabashihotaru-kannsatukai.jimdosite.com",
  "成城大学 エシカル研究会": "https://www.seijo.ac.jp/about/campus-life/club/ethical/index.html",
  "株式会社タカサ": "https://www.takasa.co.jp/",
  "学生環境団体SONE": "https://www.cuc.ac.jp/index.html",
  "ニッセイサステナプロジェクト「にっせーのせ！」×学生 共創プロジェクト": "https://www.nissay.co.jp/sustainability/sustainability_project/",
  "NPO法人国際ボランティア学生協会": "https://share.google/Ftiupr8BwVHdzEWcN",
  "株式会社 ＴＯＡシブル": "https://toaxible.com/",
  "みどり産業株式会社": "https://www.midori-sangyou.co.jp/",
  "日本大学生産工学部 環境安全工学科": "https://www.en.cit.nihon-u.ac.jp/",
  "千葉工業大学 南澤研究室": "https://chibatech.jp/about/sdgs/",
  "一般財団法人 千葉県環境財団": "https://ckz.jp/",
  "社会福祉法人あかね ワークアイ・船橋": "https://akane-net.or.jp",
  "元気ちば！健康チャレンジ事業事務局": "https://chi-value.com",
  "特定非営利活動法人ちば里山センター": "https://chiba-satoyama.net/",
  "里山Bewahrung": "https://satoyamabewahrung.wixsite.com/4seasons",
  "特定非営利活動法人環境パートナーシップちば": "https://kanpachiba.com/",
  "環境カウンセラー千葉県協議会": "https://ecchiba.sakura.ne.jp",
  "首都圏CCS株式会社": "https://mccs.inpex.co.jp/",
  "千葉県環境生活部 循環型社会推進課": "https://www.pref.chiba.lg.jp/shigen/",
  "千葉県環境生活部 水質保全課": "http://www.pref.chiba.lg.jp/suiho/index.html",
  "印旛沼流域水循環健全化会議（千葉県水質保全課・河川環境課）": "https://inba-numa.com/",
  "千葉県環境生活部 自然保護課 生物多様性センター": "https://www.bdcchiba.jp/",
  "千葉県環境生活部 温暖化対策推進課": "https://www.pref.chiba.lg.jp/cate/km/kankyou/chikyuukankyou/index.html",
  "千葉県環境生活部 千葉県消費者センター": "https://pref.chiba.lg.jp/customer/index.html",
  "千葉県環境生活部 県民生活課": "https://www.pref.chiba.lg.jp/kkbunka/npo/nponet-link.html",
  "千葉県環境生活部 千葉県環境研究センター（千葉県気候変動適応センター）": "https://www.pref.chiba.lg.jp/wit/",
  "千葉県環境生活部 中央博物館": "https://www.chiba-muse.or.jp/NATURAL/",
  "千葉県防災危機管理部 危機管理政策課地域防災支援室": "https://www.pref.chiba.lg.jp/bousaik/",
  "千葉県農林水産部 環境農業推進課みどり・耕畜連携推進室": "https://stg3.pbl.pref.chiba.lg.jp/annou/index.html",
  "第46回全国豊かな海づくり大会千葉県実行委員会（千葉県水産課）": "https://www.pref.chiba.lg.jp/cate/ssk/nourinsuisan/suisan/umidukuri/",
  "千葉県ブルーカーボン推進協議会（千葉県漁業資源課）": "https://www.pref.chiba.lg.jp/gyoshigen/moba/bluecarbon.html",
  "千葉県県土整備部下水道課【（公財）千葉県下水道公社と共同出展】": "https://www.pref.chiba.lg.jp/gesui/",
  "千葉県企業局管理部 業務振興課": "https://www.pref.chiba.lg.jp/kigyou/main/top.html",
  "千葉市脱炭素先行地域推進コンソーシアム": "https://www.city.chiba.jp/decarbonizationleadingarea/consortium/index.html",
  "千葉市環境局": "https://www.city.chiba.jp/kankyo/kankyohozen/somu/index.html",
  "千葉市消費生活センター": "https://www.city.chiba.jp/shimin/seikatsubunka/shohi/index.html",
  "千葉市脱炭素推進課": "https://www.city.chiba.jp/kankyo/kankyohozen/datsutanso/index.html",
  "千葉市地球温暖化対策地域協議会（運営主体：千葉市脱炭素推進課）": "https://www.city.chiba.jp/kankyo/kankyohozen/datsutanso/index.html",
  "千葉市廃棄物対策課": "https://www.city.chiba.jp/kankyo/junkan/haikibutsu/index.html"
};
