window.ECOMESSE_ONLINE_EXHIBITORS = [
  { name: "千葉大学 予防医学センター エコチル調査千葉ユニットセンター", description: "赤ちゃんがおなかにいる時から、子どもの成長と環境の関係を長く見守る「エコチル調査」。全国約10万組の親子が参加する大きな研究を、やさしい映像で紹介します。アレルギーや発達、暮らしの環境はどうつながる？未来の子どもたちの健康を守るために、親子で一緒に考えてみませんか。家族の未来を話すきっかけにも。", image: "online-01-ecochil.png", videoUrl: "https://youtu.be/ReB4FG64xN0", websiteUrl: "https://cpms.chiba-u.jp/kodomo/" },
  { name: "自然エネルギーを広めるネットワークちば（リネットちば）", description: "太陽の光や風の力で、私たちのまちを元気にできる？千葉県内で自然エネルギーを広げる14団体の活動を紹介します。畑の上の太陽光発電、地域の電力、防災に役立つ蓄電池など、身近な工夫がいっぱい。地球にやさしい未来の暮らしを、親子で発見してみましょう！家でできる省エネのヒントも見つかるかもしれません。", image: "リネットちば202606会員団体.jpg", videoUrl: "https://www.youtube.com/watch?v=ETKeBTdvCEs", websiteUrl: "https://www.renet-chiba.net/" },
  { name: "NACS千葉分科会（日本消費生活アドバイザー・コンサルタント・相談員協会）", description: "「相続」って大人だけの難しい話？実は、家族で大切なものや思いをどう受け継ぐかを考えることです。介護などで支えた人の寄与分、生前にもらった特別受益、お墓や仏壇の祭祀承継をやさしく解説。家族が仲良く暮らし続けるために、親子で“伝えることの大切さ”を学べます。今からできる備えを一緒に探しましょう。", image: "online-03-nacs-chiba.png", videoUrl: "https://youtu.be/-G3OL41aU7k", websiteUrl: "" },
  { name: "八千代市ほたるの里づくり実行委員会", description: "市民と生き物に触れ、自然体験を通して、地域との繋がりや生態系の保全など楽しく学ぶ場です。主に水辺の生き物の保全とヘイケボタルの再生をシンボルに、環境整備活動や生き物探検活動などを紹介します。", image: "八千代市ほたるの里づくり実行委員会.png", videoUrl: "https://youtu.be/5ZQbPoYNnTg", websiteUrl: "https://www.city.yachiyo.lg.jp/soshiki/40/3728.html" },
  { name: "千葉県健康福祉部 健康づくり支援課", description: "同じ量のお酒でも、年齢・性別・体質によって体への影響は違います。若い人や高齢者が気をつけることは？性別による違いはあるの？身近な疑問から、お酒と上手に付き合っていくためのポイントをわかりやすく紹介します。ご自身やご家族の健康を考えるきっかけとして、ぜひご覧ください。", image: "online-05-chiba-health.png", videoUrl: "https://youtu.be/NCPn0cAEDM4", websiteUrl: "https://www.pref.chiba.lg.jp/kenzu/" },
  { name: "千葉県農林水産部 森林課", description: "会社の人たちが森へ出かけ、苗木を植え、草を刈り、未来の森林を育てる「法人の森事業」。企業・団体と千葉県が力を合わせ、海岸林や県有林を守る仕組みを紹介します。森はどうやって育ち、私たちの暮らしを守るの？働くことと社会貢献のつながりを、親子で楽しく学べます。身近な木や森を見る目がきっと変わります。", image: "online-06-chiba-forest.png", videoUrl: "https://youtu.be/VSWl5-yXMI4", websiteUrl: "https://www.pref.chiba.lg.jp/shinrin/hojin/" },
  { name: "千葉県 公園緑地課", description: "", image: "", videoUrl: "", websiteUrl: "https://www.pref.chiba.lg.jp/shinrin/hojin/" }
];
